### ISSUE TITLE
Get all GPIO state resets to default state rather than showing current state

### ISSUE THREAD

**Issue by sivansh11** [vicharak-in/vicharak-config#11]
as said in the title, either this is a bug, or it is very missleading, it should say reset to default state in case its not a bug

**Comment by sivansh11** [comment]
apparently, get option changes the pin from output to input mode which starts reading the current signals, so it is correct behaviour.
Maybe mention this in a note/comment for new users who dont have the background knowledge ?

**Comment by djkabutar** [comment]
@shailparmar03 should I close this issue?

**Comment by sivansh11** [comment]
I really would suggest adding a small note that get/set changes gpio to input/output which may not be the desiered behaviour
